// en.js - English Translations
const translations_en = {
    pageTitle: "Payment & Checkout",
    checkoutHeader: "Checkout",
    reviewOrder: "Review your order and choose payment method.",
    yourOrder: "Your Order",
    productNameHeader: "Product",
    quantity: "Qty",
    price: "Price",
    total: "Total",
    noItemsSelected: "No items selected. Please go back to the product catalog.",
    orderTotal: "Order Total:",
    currencySAR: "SAR",
    customerInformation: "Customer Information",
    fullName: "Full Name",
    emailAddress: "Email Address",
    emailPlaceholder: "email@example.com",
    phoneNumber: "Phone Number",
    phonePlaceholder: "+1 234 567 8900",
    paymentOptions: "Payment Options",
    applePay: "Apple Pay",
    creditDebitCard: "Credit/Debit Card",
    cardNumber: "Card Number",
    cardNumberPlaceholder: "XXXX XXXX XXXX XXXX",
    expiryDate: "Expiry Date",
    expiryDatePlaceholder: "MM/YY",
    cvv: "CVV",
    cvvPlaceholder: "123",
    nameOnCard: "Name on Card",
    nameOnCardPlaceholder: "Full Name",
    payNow: "Pay Now",
    enterCardDetails: "Please enter all card details.",
    enterCustomerDetails: "Please enter your full name, email, and phone number.",
    paymentFailed: "Payment failed: ",
    unknownError: "Unknown error",
    networkError: "An error occurred during payment. Please try again."
};
