// ar.js - Arabic Translations
const translations_ar = {
    pageTitle: "الدفع وإتمام الطلب",
    checkoutHeader: "الدفع",
    reviewOrder: "راجع طلبك واختر طريقة الدفع.",
    yourOrder: "طلبك",
    productNameHeader: "المنتج",
    quantity: "الكمية",
    price: "السعر",
    total: "الإجمالي",
    noItemsSelected: "لم يتم اختيار أي عناصر. يرجى العودة إلى كتالوج المنتجات.",
    orderTotal: "إجمالي الطلب:",
    currencySAR: "ريال",
    customerInformation: "معلومات العميل",
    fullName: "الاسم الكامل",
    emailAddress: "عنوان البريد الإلكتروني",
    emailPlaceholder: "البريد الإلكتروني",
    phoneNumber: "رقم الهاتف",
    phonePlaceholder: "+٩٦٦ ٥٠ ١٢٣ ٤٥٦٧", // Example for Saudi number
    paymentOptions: "خيارات الدفع",
    applePay: "أبل باي",
    creditDebitCard: "بطاقة ائتمان/خصم",
    cardNumber: "رقم البطاقة",
    cardNumberPlaceholder: "XXXX XXXX XXXX XXXX",
    expiryDate: "تاريخ انتهاء الصلاحية",
    expiryDatePlaceholder: "شهر/سنة",
    cvv: "CVV",
    cvvPlaceholder: "123",
    nameOnCard: "الاسم على البطاقة",
    nameOnCardPlaceholder: "الاسم الكامل",
    payNow: "ادفع الآن",
    enterCardDetails: "الرجاء إدخال جميع تفاصيل البطاقة.",
    enterCustomerDetails: "الرجاء إدخال اسمك الكامل وبريدك الإلكتروني ورقم هاتفك.",
    paymentFailed: "فشل الدفع: ",
    unknownError: "خطأ غير معروف",
    networkError: "حدث خطأ أثناء الدفع. الرجاء المحاولة مرة أخرى."
};
